In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import resample 
from sklearn.preprocessing import OneHotEncoder

In [4]:
Data = pd.read_csv("/home/omnix/Desktop/E-Commerce/E-commerce_EDA/Data/Raw_data.csv")
Data

,order_id,order_date,customer_id,customer_name,customer_email,customer_segment,product_name,quantity,unit_price,discount_percent,...,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,review_text,return_flag,return_reason
0,ORD0009460,2023-11-16,CUST00544,Alok Yadav,alok.yadav@hotmail.com,Silver,Monitor,2,13834.28,0.24,...,Delhi,96.20,Express,Debit Card,Paid,TXN27014,2.0,NaN,False,NaN
1,ORD0005459,2023-06-24,CUST01462,Amit Gupta,amit.gupta@yahoo.com,Premium,Gaming Chair,1,60000,2.50,...,Chennai,59.46,Express,Debit Card,Pending,TXN93469,NaN,Late delivery,False,NaN
2,ORD0000813,2024-12-07,CUST02713,Priya Verma,priya.verma@yahoo.com,Standard,Printer,2,12684.38,0.31,...,Hyderabad,48.06,Same Day,COD,Pending,TXN17450,2.0,Average,False,NaN
3,ORD0018416,2024-06-25,CUST02105,Alok Sharma,alok.sharma@hotmail.com,Standard,Desk Lamp,1,1557.14,0.39,...,Mumbai,96.92,Same Day,UPI,Paid,TXN71839,5.0,NaN,False,NaN
4,ORD0002141,2024-06-26,CUST02110,Ritu Joshi,ritu.joshi@rediffmail.com,Standard,Smart Watch,1,8478.67,0.13,...,Pune,62.92,Standard,Debit Card,Paid,TXN73153,5.0,Damaged,True,Better price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,ORD0013297,2023-05-04,CUST00252,Sunil Verma,sunil.verma@rediffmail.com,New,Tablet,8,27304.63,0.24,...,Mumbai,3.13,Standard,UPI,Paid,TXN13843,4.0,Poor quality,False,NaN
20396,ORD0011311,2023-09-20,CUST02059,Neha Malhotra,neha.malhotra@gmail.com,Silver,Router,1,3348.36,0.07,...,Hyderabad,80.69,Express,Credit Card,Failed,TXN54224,4.0,NaN,NaN,NaN
20397,ORD0009436,2024-01-25,CUST01260,Amit Yadav,amit.yadav@yahoo.com,New,Desk Lamp,10,1620.8,NaN,...,Jaipur,66.51,Express,Credit Card,Paid,TXN27200,1.0,???,False,NaN
20398,ORD0019129,2024-04-12,CUST02705,Pooja Yadav,pooja.yadav@gmail.com,Standard,Headphones,1,NaN,0.17,...,Mumbai,76.95,Express,Debit Card,Paid,TXN12729,5.0,Poor quality,False,NaN
20399,ORD0007254,2024-11-14,CUST00932,Amit Verma,amit.verma@yahoo.com,Standard,Laptop,3,51076.41,0.13,...,Hyderabad,69.32,Standard,NetBanking,Paid,TXN35054,4.0,Will buy again,False,NaN

In [5]:
Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20400 entries, 0 to 20399
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          20400 non-null  str
 1   order_date        20242 non-null  str
 2   customer_id       20400 non-null  str
 3   customer_name     19293 non-null  str
 4   customer_email    20015 non-null  str
 5   customer_segment  19750 non-null  str
 6   product_name      20400 non-null  str
 7   quantity          20276 non-null  str
 8   unit_price        19993 non-null  str
 9   discount_percent  19561 non-null  float64
 10  shipping_region   19974 non-null  str
 11  shipping_city     20400 non-null  str
 12  shipping_cost     20246 non-null  float64
 13  shipping_method   19368 non-null  str
 14  payment_method    19993 non-null  str
 15  payment_status    19751 non-null  str
 16  transaction_id    20400 non-null  str
 17  rating            18965 non-null  float64
 18  review_text       17019 non-null  str
 19  return_flag       19588 non-null  str
 20  return_reason     1563 non-null   str
dtypes: float64(3), str(18)
memory usage: 3.3 MB

In [6]:
Data.isnull().sum()

order_id                0
order_date            158
customer_id             0
customer_name        1107
customer_email        385
customer_segment      650
product_name            0
quantity              124
unit_price            407
discount_percent      839
shipping_region       426
shipping_city           0
shipping_cost         154
shipping_method      1032
payment_method        407
payment_status        649
transaction_id          0
rating               1435
review_text          3381
return_flag           812
return_reason       18837
dtype: int64

In [9]:
Data['order_date']=Data['order_date'].fillna(Data['order_date'].mode()[0])
Data['customer_name'] =Data['customer_name'].fillna(Data['customer_name'].mode()[0])
Data['customer_email'] = Data['customer_email'].fillna(Data['customer_email'].mode()[0])
Data['customer_segment'] =Data['customer_segment'].fillna(Data['customer_segment'].mode()[0])
Data['quantity'] = Data['quantity'].fillna(Data['quantity'].mode()[0])
Data['unit_price'] = Data['unit_price'].fillna(Data['unit_price'].mode()[0])
Data['discount_percent'] = Data['discount_percent'].fillna(Data['discount_percent'].mean())
Data['shipping_region'] = Data['shipping_region'].fillna(Data['shipping_region'].mode()[0])
Data['shipping_cost'] = Data['shipping_cost'].fillna(Data['shipping_cost'].mean())
Data['shipping_method'] = Data['shipping_method'].fillna(Data['shipping_method'].mode()[0])
Data['payment_method'] = Data['payment_method'].fillna(Data['payment_method'].mode()[0])
Data['payment_status'] =Data['payment_status'].fillna(Data['payment_status'].mode()[0])
Data['rating'] = Data['rating'].fillna(Data['rating'].mean())
Data['review_text'] =Data['review_text'].fillna(Data['review_text'].mode()[0])
Data['return_flag'] = Data['return_flag'].fillna(Data['return_flag'].mode()[0])
Data['return_reason'] =Data['return_reason'].fillna(Data['return_reason'].mode()[0])

In [10]:
Data.isnull().sum()

order_id            0
order_date          0
customer_id         0
customer_name       0
customer_email      0
customer_segment    0
product_name        0
quantity            0
unit_price          0
discount_percent    0
shipping_region     0
shipping_city       0
shipping_cost       0
shipping_method     0
payment_method      0
payment_status      0
transaction_id      0
rating              0
review_text         0
return_flag         0
return_reason       0
dtype: int64

In [11]:
Data

,order_id,order_date,customer_id,customer_name,customer_email,customer_segment,product_name,quantity,unit_price,discount_percent,...,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,review_text,return_flag,return_reason
0,ORD0009460,2023-11-16,CUST00544,Alok Yadav,alok.yadav@hotmail.com,Silver,Monitor,2,13834.28,0.240000,...,Delhi,96.20,Express,Debit Card,Paid,TXN27014,2.000000,Will buy again,False,Better price
1,ORD0005459,2023-06-24,CUST01462,Amit Gupta,amit.gupta@yahoo.com,Premium,Gaming Chair,1,60000,2.500000,...,Chennai,59.46,Express,Debit Card,Pending,TXN93469,3.789876,Late delivery,False,Better price
2,ORD0000813,2024-12-07,CUST02713,Priya Verma,priya.verma@yahoo.com,Standard,Printer,2,12684.38,0.310000,...,Hyderabad,48.06,Same Day,COD,Pending,TXN17450,2.000000,Average,False,Better price
3,ORD0018416,2024-06-25,CUST02105,Alok Sharma,alok.sharma@hotmail.com,Standard,Desk Lamp,1,1557.14,0.390000,...,Mumbai,96.92,Same Day,UPI,Paid,TXN71839,5.000000,Will buy again,False,Better price
4,ORD0002141,2024-06-26,CUST02110,Ritu Joshi,ritu.joshi@rediffmail.com,Standard,Smart Watch,1,8478.67,0.130000,...,Pune,62.92,Standard,Debit Card,Paid,TXN73153,5.000000,Damaged,True,Better price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,ORD0013297,2023-05-04,CUST00252,Sunil Verma,sunil.verma@rediffmail.com,New,Tablet,8,27304.63,0.240000,...,Mumbai,3.13,Standard,UPI,Paid,TXN13843,4.000000,Poor quality,False,Better price
20396,ORD0011311,2023-09-20,CUST02059,Neha Malhotra,neha.malhotra@gmail.com,Silver,Router,1,3348.36,0.070000,...,Hyderabad,80.69,Express,Credit Card,Failed,TXN54224,4.000000,Will buy again,False,Better price
20397,ORD0009436,2024-01-25,CUST01260,Amit Yadav,amit.yadav@yahoo.com,New,Desk Lamp,10,1620.8,0.226173,...,Jaipur,66.51,Express,Credit Card,Paid,TXN27200,1.000000,???,False,Better price
20398,ORD0019129,2024-04-12,CUST02705,Pooja Yadav,pooja.yadav@gmail.com,Standard,Headphones,1,contact,0.170000,...,Mumbai,76.95,Express,Debit Card,Paid,TXN12729,5.000000,Poor quality,False,Better price
20399,ORD0007254,2024-11-14,CUST00932,Amit Verma,amit.verma@yahoo.com,Standard,Laptop,3,51076.41,0.130000,...,Hyderabad,69.32,Standard,NetBanking,Paid,TXN35054,4.000000,Will buy again,False,Better price

In [20]:
# Data['order_id']=Data['order_id'].str.split('D').str[1].astype(int)
# Data['customer_id']=Data['customer_id'].str.split('T').str[1].astype(int)
Data['quantity'] = pd.to_numeric(Data['quantity'], errors='coerce').astype('Int64')
Data['unit_price'] = pd.to_numeric(Data['unit_price'],errors='coerce').astype(float)
Data['transaction_id'] = Data['transaction_id'].str.split('N').str[1].astype(int)

In [21]:
Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20400 entries, 0 to 20399
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          20400 non-null  int64
 1   order_date        20400 non-null  str
 2   customer_id       20400 non-null  int64
 3   customer_name     20400 non-null  str
 4   customer_email    20400 non-null  str
 5   customer_segment  20400 non-null  str
 6   product_name      20400 non-null  str
 7   quantity          19894 non-null  Int64
 8   unit_price        19578 non-null  float64
 9   discount_percent  20400 non-null  float64
 10  shipping_region   20400 non-null  str
 11  shipping_city     20400 non-null  str
 12  shipping_cost     20400 non-null  float64
 13  shipping_method   20400 non-null  str
 14  payment_method    20400 non-null  str
 15  payment_status    20400 non-null  str
 16  transaction_id    20400 non-null  int64
 17  rating            20400 non-null  float64
 18  review_text       20400 non-null  str
 19  return_flag       20400 non-null  str
 20  return_reason     20400 non-null  str
dtypes: Int64(1), float64(4), int64(3), str(13)
memory usage: 3.3 MB

In [22]:
Data

,order_id,order_date,customer_id,customer_name,customer_email,customer_segment,product_name,quantity,unit_price,discount_percent,...,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,review_text,return_flag,return_reason
0,9460,2023-11-16,544,Alok Yadav,alok.yadav@hotmail.com,Silver,Monitor,2,13834.28,0.240000,...,Delhi,96.20,Express,Debit Card,Paid,27014,2.000000,Will buy again,False,Better price
1,5459,2023-06-24,1462,Amit Gupta,amit.gupta@yahoo.com,Premium,Gaming Chair,1,60000.00,2.500000,...,Chennai,59.46,Express,Debit Card,Pending,93469,3.789876,Late delivery,False,Better price
2,813,2024-12-07,2713,Priya Verma,priya.verma@yahoo.com,Standard,Printer,2,12684.38,0.310000,...,Hyderabad,48.06,Same Day,COD,Pending,17450,2.000000,Average,False,Better price
3,18416,2024-06-25,2105,Alok Sharma,alok.sharma@hotmail.com,Standard,Desk Lamp,1,1557.14,0.390000,...,Mumbai,96.92,Same Day,UPI,Paid,71839,5.000000,Will buy again,False,Better price
4,2141,2024-06-26,2110,Ritu Joshi,ritu.joshi@rediffmail.com,Standard,Smart Watch,1,8478.67,0.130000,...,Pune,62.92,Standard,Debit Card,Paid,73153,5.000000,Damaged,True,Better price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,13297,2023-05-04,252,Sunil Verma,sunil.verma@rediffmail.com,New,Tablet,8,27304.63,0.240000,...,Mumbai,3.13,Standard,UPI,Paid,13843,4.000000,Poor quality,False,Better price
20396,11311,2023-09-20,2059,Neha Malhotra,neha.malhotra@gmail.com,Silver,Router,1,3348.36,0.070000,...,Hyderabad,80.69,Express,Credit Card,Failed,54224,4.000000,Will buy again,False,Better price
20397,9436,2024-01-25,1260,Amit Yadav,amit.yadav@yahoo.com,New,Desk Lamp,10,1620.80,0.226173,...,Jaipur,66.51,Express,Credit Card,Paid,27200,1.000000,???,False,Better price
20398,19129,2024-04-12,2705,Pooja Yadav,pooja.yadav@gmail.com,Standard,Headphones,1,NaN,0.170000,...,Mumbai,76.95,Express,Debit Card,Paid,12729,5.000000,Poor quality,False,Better price
20399,7254,2024-11-14,932,Amit Verma,amit.verma@yahoo.com,Standard,Laptop,3,51076.41,0.130000,...,Hyderabad,69.32,Standard,NetBanking,Paid,35054,4.000000,Will buy again,False,Better price

In [27]:
Data['order_date'] = pd.to_datetime(Data['order_date'], errors='coerce', 
                                     format='mixed', dayfirst=True)


Data['Year'] = Data['order_date'].dt.year.astype('Int64')
Data['Month'] = Data['order_date'].dt.month.astype('Int64')
Data['Day'] = Data['order_date'].dt.day.astype('Int64')


Data.drop('order_date', axis=1, inplace=True)  # Changed 'oredr_date' to 'order_date'

In [28]:
Data

,order_id,customer_id,customer_name,customer_email,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_region,...,payment_method,payment_status,transaction_id,rating,review_text,return_flag,return_reason,Year,Month,Day
0,9460,544,Alok Yadav,alok.yadav@hotmail.com,Silver,Monitor,2,13834.28,0.240000,East,...,Debit Card,Paid,27014,2.000000,Will buy again,False,Better price,2023,11,16
1,5459,1462,Amit Gupta,amit.gupta@yahoo.com,Premium,Gaming Chair,1,60000.00,2.500000,South,...,Debit Card,Pending,93469,3.789876,Late delivery,False,Better price,2023,6,24
2,813,2713,Priya Verma,priya.verma@yahoo.com,Standard,Printer,2,12684.38,0.310000,North,...,COD,Pending,17450,2.000000,Average,False,Better price,2024,7,12
3,18416,2105,Alok Sharma,alok.sharma@hotmail.com,Standard,Desk Lamp,1,1557.14,0.390000,East,...,UPI,Paid,71839,5.000000,Will buy again,False,Better price,2024,6,25
4,2141,2110,Ritu Joshi,ritu.joshi@rediffmail.com,Standard,Smart Watch,1,8478.67,0.130000,South,...,Debit Card,Paid,73153,5.000000,Damaged,True,Better price,2024,6,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,13297,252,Sunil Verma,sunil.verma@rediffmail.com,New,Tablet,8,27304.63,0.240000,North,...,UPI,Paid,13843,4.000000,Poor quality,False,Better price,2023,4,5
20396,11311,2059,Neha Malhotra,neha.malhotra@gmail.com,Silver,Router,1,3348.36,0.070000,South,...,Credit Card,Failed,54224,4.000000,Will buy again,False,Better price,2023,9,20
20397,9436,1260,Amit Yadav,amit.yadav@yahoo.com,New,Desk Lamp,10,1620.80,0.226173,South,...,Credit Card,Paid,27200,1.000000,???,False,Better price,2024,1,25
20398,19129,2705,Pooja Yadav,pooja.yadav@gmail.com,Standard,Headphones,1,NaN,0.170000,West,...,Debit Card,Paid,12729,5.000000,Poor quality,False,Better price,2024,12,4
20399,7254,932,Amit Verma,amit.verma@yahoo.com,Standard,Laptop,3,51076.41,0.130000,North,...,NetBanking,Paid,35054,4.000000,Will buy again,False,Better price,2024,11,14

In [30]:
Data.duplicated().sum()

np.int64(400)

In [31]:
Data.drop_duplicates(inplace=True)

In [33]:
Data.drop(Data[Data['quantity']<=0].index,inplace=True)

In [35]:
Data.drop(Data[Data['unit_price']<=0].index,inplace=True)

In [38]:
Data.drop(Data[Data['discount_percent']<=0].index,inplace=True)

In [41]:
Data.drop(Data[Data['rating']<=0].index,inplace=True)

In [45]:
Data['quantity'] = Data['quantity'].fillna(1)

In [52]:
Data['unit_price']=Data['unit_price'].fillna(Data['unit_price'].mean())
Data['Year']=Data['Year'].fillna(Data['Year'].mode()[0])
Data['Month'] =Data['Month'].fillna(Data['Month'].mode()[0])
Data['Day'] = Data['Day'].fillna(Data['Day'].mode()[0])

In [53]:
Data.isnull().sum()

order_id            0
customer_id         0
customer_name       0
customer_email      0
customer_segment    0
product_name        0
quantity            0
unit_price          0
discount_percent    0
shipping_region     0
shipping_city       0
shipping_cost       0
shipping_method     0
payment_method      0
payment_status      0
transaction_id      0
rating              0
review_text         0
return_flag         0
return_reason       0
Year                0
Month               0
Day                 0
dtype: int64

In [57]:
Data.drop('review_text',axis=1,inplace=True)

In [ ]:
Data.drop('')

In [60]:
Data.describe()

,order_id,customer_id,quantity,unit_price,discount_percent,shipping_cost,transaction_id,rating,Year,Month,Day
count,17820.000000,17820.000000,17820.0,17820.000000,17820.000000,17820.000000,17820.000000,17820.000000,17820.0,17820.0,17820.0
mean,10008.874018,1497.938272,4.429574,9447.351522,0.241219,49.420019,54928.678339,3.916413,2023.508698,6.277385,14.465152
std,5780.951414,870.061269,3.092877,15293.528368,0.290509,29.235996,26080.206907,1.163655,0.499938,3.534505,7.902733
min,1.000000,1.000000,1.0,170.080000,0.010000,-99.170000,10001.000000,1.000000,2023.0,1.0,1.0
25%,5007.750000,738.000000,1.0,2012.010000,0.110000,25.057500,32023.000000,3.000000,2023.0,3.0,8.0
50%,10015.000000,1494.000000,4.0,3681.105000,0.220000,49.515000,54922.000000,4.000000,2024.0,6.0,14.0
75%,15034.250000,2257.000000,7.0,11285.105000,0.300000,74.090000,77407.500000,5.000000,2024.0,9.0,21.0
max,20000.000000,3000.000000,10.0,275000.000000,2.500000,100.000000,99998.000000,5.000000,2024.0,12.0,28.0

In [62]:
Data['total_revenue'] = (Data['quantity'] * Data['unit_price'] * (1 - Data['discount_percent'])) + Data['shipping_cost']

In [65]:
Data.drop(Data[Data['total_revenue']<=0].index,inplace=True)

In [66]:
Data

,order_id,customer_id,customer_name,customer_email,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_region,...,payment_method,payment_status,transaction_id,rating,return_flag,return_reason,Year,Month,Day,total_revenue
0,9460,544,Alok Yadav,alok.yadav@hotmail.com,Silver,Monitor,2,13834.280000,0.240000,East,...,Debit Card,Paid,27014,2.0,False,Better price,2023,11,16,21124.3056
2,813,2713,Priya Verma,priya.verma@yahoo.com,Standard,Printer,2,12684.380000,0.310000,North,...,COD,Pending,17450,2.0,False,Better price,2024,7,12,17552.5044
3,18416,2105,Alok Sharma,alok.sharma@hotmail.com,Standard,Desk Lamp,1,1557.140000,0.390000,East,...,UPI,Paid,71839,5.0,False,Better price,2024,6,25,1046.7754
4,2141,2110,Ritu Joshi,ritu.joshi@rediffmail.com,Standard,Smart Watch,1,8478.670000,0.130000,South,...,Debit Card,Paid,73153,5.0,True,Better price,2024,6,26,7439.3629
5,18330,2400,Amit Verma,@.com,Standard,Gaming Chair,2,11976.960000,0.190000,West,...,UPI,Paid,69826,4.0,Yes,Damaged,2023,6,12,19500.2352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,13297,252,Sunil Verma,sunil.verma@rediffmail.com,New,Tablet,8,27304.630000,0.240000,North,...,UPI,Paid,13843,4.0,False,Better price,2023,4,5,166015.2804
20396,11311,2059,Neha Malhotra,neha.malhotra@gmail.com,Silver,Router,1,3348.360000,0.070000,South,...,Credit Card,Failed,54224,4.0,False,Better price,2023,9,20,3194.6648
20397,9436,1260,Amit Yadav,amit.yadav@yahoo.com,New,Desk Lamp,10,1620.800000,0.226173,South,...,Credit Card,Paid,27200,1.0,False,Better price,2024,1,25,12608.69806
20398,19129,2705,Pooja Yadav,pooja.yadav@gmail.com,Standard,Headphones,1,9447.351522,0.170000,West,...,Debit Card,Paid,12729,5.0,False,Better price,2024,12,4,7918.251763
20399,7254,932,Amit Verma,amit.verma@yahoo.com,Standard,Laptop,3,51076.410000,0.130000,North,...,NetBanking,Paid,35054,4.0,False,Better price,2024,11,14,133378.7501

In [67]:
# Quick fix for emails
Data['customer_email'] = Data['customer_email'].fillna('unknown@email.com')
Data['customer_email'] = Data['customer_email'].apply(lambda x: x if '@' in str(x) else f"{x}@email.com")
Data['customer_email'] = Data['customer_email'].str.replace('@@', '@')

# Quick fix for return reasons
Data.loc[Data['return_flag'] == False, 'return_reason'] = ''

In [69]:
Data.drop('customer_email',axis=1,inplace=True)

In [71]:
Data.drop('return_reason',axis=1,inplace=True)

In [73]:
Data.drop('shipping_region',axis=1,inplace=True)

In [75]:
Data.drop('order_id',axis=1,inplace=True)

In [76]:
Data

,customer_id,customer_name,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,return_flag,Year,Month,Day,total_revenue
0,544,Alok Yadav,Silver,Monitor,2,13834.280000,0.240000,Delhi,96.20,Express,Debit Card,Paid,27014,2.0,False,2023,11,16,21124.3056
2,2713,Priya Verma,Standard,Printer,2,12684.380000,0.310000,Hyderabad,48.06,Same Day,COD,Pending,17450,2.0,False,2024,7,12,17552.5044
3,2105,Alok Sharma,Standard,Desk Lamp,1,1557.140000,0.390000,Mumbai,96.92,Same Day,UPI,Paid,71839,5.0,False,2024,6,25,1046.7754
4,2110,Ritu Joshi,Standard,Smart Watch,1,8478.670000,0.130000,Pune,62.92,Standard,Debit Card,Paid,73153,5.0,True,2024,6,26,7439.3629
5,2400,Amit Verma,Standard,Gaming Chair,2,11976.960000,0.190000,Pune,97.56,Standard,UPI,Paid,69826,4.0,Yes,2023,6,12,19500.2352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,252,Sunil Verma,New,Tablet,8,27304.630000,0.240000,Mumbai,3.13,Standard,UPI,Paid,13843,4.0,False,2023,4,5,166015.2804
20396,2059,Neha Malhotra,Silver,Router,1,3348.360000,0.070000,Hyderabad,80.69,Express,Credit Card,Failed,54224,4.0,False,2023,9,20,3194.6648
20397,1260,Amit Yadav,New,Desk Lamp,10,1620.800000,0.226173,Jaipur,66.51,Express,Credit Card,Paid,27200,1.0,False,2024,1,25,12608.69806
20398,2705,Pooja Yadav,Standard,Headphones,1,9447.351522,0.170000,Mumbai,76.95,Express,Debit Card,Paid,12729,5.0,False,2024,12,4,7918.251763
20399,932,Amit Verma,Standard,Laptop,3,51076.410000,0.130000,Hyderabad,69.32,Standard,NetBanking,Paid,35054,4.0,False,2024,11,14,133378.7501

In [79]:
Data['returned'] = Data['return_flag'].map({'False':0,"No":0,"N":0,"True":1,"Yes":1,"Y":1})

In [77]:
Data['return_flag'].value_counts()

return_flag
False    15015
True       688
Yes        531
No         509
Y          352
N          349
Name: count, dtype: int64

In [80]:
Data

,customer_id,customer_name,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,return_flag,Year,Month,Day,total_revenue,returned
0,544,Alok Yadav,Silver,Monitor,2,13834.280000,0.240000,Delhi,96.20,Express,Debit Card,Paid,27014,2.0,False,2023,11,16,21124.3056,0
2,2713,Priya Verma,Standard,Printer,2,12684.380000,0.310000,Hyderabad,48.06,Same Day,COD,Pending,17450,2.0,False,2024,7,12,17552.5044,0
3,2105,Alok Sharma,Standard,Desk Lamp,1,1557.140000,0.390000,Mumbai,96.92,Same Day,UPI,Paid,71839,5.0,False,2024,6,25,1046.7754,0
4,2110,Ritu Joshi,Standard,Smart Watch,1,8478.670000,0.130000,Pune,62.92,Standard,Debit Card,Paid,73153,5.0,True,2024,6,26,7439.3629,1
5,2400,Amit Verma,Standard,Gaming Chair,2,11976.960000,0.190000,Pune,97.56,Standard,UPI,Paid,69826,4.0,Yes,2023,6,12,19500.2352,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,252,Sunil Verma,New,Tablet,8,27304.630000,0.240000,Mumbai,3.13,Standard,UPI,Paid,13843,4.0,False,2023,4,5,166015.2804,0
20396,2059,Neha Malhotra,Silver,Router,1,3348.360000,0.070000,Hyderabad,80.69,Express,Credit Card,Failed,54224,4.0,False,2023,9,20,3194.6648,0
20397,1260,Amit Yadav,New,Desk Lamp,10,1620.800000,0.226173,Jaipur,66.51,Express,Credit Card,Paid,27200,1.0,False,2024,1,25,12608.69806,0
20398,2705,Pooja Yadav,Standard,Headphones,1,9447.351522,0.170000,Mumbai,76.95,Express,Debit Card,Paid,12729,5.0,False,2024,12,4,7918.251763,0
20399,932,Amit Verma,Standard,Laptop,3,51076.410000,0.130000,Hyderabad,69.32,Standard,NetBanking,Paid,35054,4.0,False,2024,11,14,133378.7501,0

In [81]:
Data.drop('return_flag',axis=1,inplace=True)

In [82]:
Data

,customer_id,customer_name,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_city,shipping_cost,shipping_method,payment_method,payment_status,transaction_id,rating,Year,Month,Day,total_revenue,returned
0,544,Alok Yadav,Silver,Monitor,2,13834.280000,0.240000,Delhi,96.20,Express,Debit Card,Paid,27014,2.0,2023,11,16,21124.3056,0
2,2713,Priya Verma,Standard,Printer,2,12684.380000,0.310000,Hyderabad,48.06,Same Day,COD,Pending,17450,2.0,2024,7,12,17552.5044,0
3,2105,Alok Sharma,Standard,Desk Lamp,1,1557.140000,0.390000,Mumbai,96.92,Same Day,UPI,Paid,71839,5.0,2024,6,25,1046.7754,0
4,2110,Ritu Joshi,Standard,Smart Watch,1,8478.670000,0.130000,Pune,62.92,Standard,Debit Card,Paid,73153,5.0,2024,6,26,7439.3629,1
5,2400,Amit Verma,Standard,Gaming Chair,2,11976.960000,0.190000,Pune,97.56,Standard,UPI,Paid,69826,4.0,2023,6,12,19500.2352,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,252,Sunil Verma,New,Tablet,8,27304.630000,0.240000,Mumbai,3.13,Standard,UPI,Paid,13843,4.0,2023,4,5,166015.2804,0
20396,2059,Neha Malhotra,Silver,Router,1,3348.360000,0.070000,Hyderabad,80.69,Express,Credit Card,Failed,54224,4.0,2023,9,20,3194.6648,0
20397,1260,Amit Yadav,New,Desk Lamp,10,1620.800000,0.226173,Jaipur,66.51,Express,Credit Card,Paid,27200,1.0,2024,1,25,12608.69806,0
20398,2705,Pooja Yadav,Standard,Headphones,1,9447.351522,0.170000,Mumbai,76.95,Express,Debit Card,Paid,12729,5.0,2024,12,4,7918.251763,0
20399,932,Amit Verma,Standard,Laptop,3,51076.410000,0.130000,Hyderabad,69.32,Standard,NetBanking,Paid,35054,4.0,2024,11,14,133378.7501,0

In [83]:
# Optimized Column Order List

optimal_columns = [
    'customer_id',
    'transaction_id',
    'customer_name',
    'customer_segment',
    'product_name',
    'quantity',
    'unit_price',
    'discount_percent',
    'shipping_city',
    'shipping_method',
    'shipping_cost',
    'payment_method',
    'payment_status',
    'Year',
    'Month',
    'Day',
    'rating',
    'returned',
    'total_revenue'
]

Data=Data[optimal_columns]

In [84]:
Data

,customer_id,transaction_id,customer_name,customer_segment,product_name,quantity,unit_price,discount_percent,shipping_city,shipping_method,shipping_cost,payment_method,payment_status,Year,Month,Day,rating,returned,total_revenue
0,544,27014,Alok Yadav,Silver,Monitor,2,13834.280000,0.240000,Delhi,Express,96.20,Debit Card,Paid,2023,11,16,2.0,0,21124.3056
2,2713,17450,Priya Verma,Standard,Printer,2,12684.380000,0.310000,Hyderabad,Same Day,48.06,COD,Pending,2024,7,12,2.0,0,17552.5044
3,2105,71839,Alok Sharma,Standard,Desk Lamp,1,1557.140000,0.390000,Mumbai,Same Day,96.92,UPI,Paid,2024,6,25,5.0,0,1046.7754
4,2110,73153,Ritu Joshi,Standard,Smart Watch,1,8478.670000,0.130000,Pune,Standard,62.92,Debit Card,Paid,2024,6,26,5.0,1,7439.3629
5,2400,69826,Amit Verma,Standard,Gaming Chair,2,11976.960000,0.190000,Pune,Standard,97.56,UPI,Paid,2023,6,12,4.0,1,19500.2352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,252,13843,Sunil Verma,New,Tablet,8,27304.630000,0.240000,Mumbai,Standard,3.13,UPI,Paid,2023,4,5,4.0,0,166015.2804
20396,2059,54224,Neha Malhotra,Silver,Router,1,3348.360000,0.070000,Hyderabad,Express,80.69,Credit Card,Failed,2023,9,20,4.0,0,3194.6648
20397,1260,27200,Amit Yadav,New,Desk Lamp,10,1620.800000,0.226173,Jaipur,Express,66.51,Credit Card,Paid,2024,1,25,1.0,0,12608.69806
20398,2705,12729,Pooja Yadav,Standard,Headphones,1,9447.351522,0.170000,Mumbai,Express,76.95,Debit Card,Paid,2024,12,4,5.0,0,7918.251763
20399,932,35054,Amit Verma,Standard,Laptop,3,51076.410000,0.130000,Hyderabad,Standard,69.32,NetBanking,Paid,2024,11,14,4.0,0,133378.7501

In [85]:
Data.to_csv("/home/omnix/Desktop/E-Commerce/E-commerce_EDA/Data/Cleaned.csv")